// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gojhagvztagmxnhpgafa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdvamhhZ3Z6dGFnbXhuaHBnYWZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MjA0NjcsImV4cCI6MjA2MDQ5NjQ2N30.EO3RLbgHZdZeaxLgVoBcTj5cpVh_rvyH4Nnz8L5Q9xI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);